language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: BNn6YSN7GM00lWrPMQoBQMpjgHNn6rOj0SrXHzQygC15bcmoH1ubRfMGBlUeddqYO8RnvVwxfYEZC+bEcAjloLcGmgMaogRVfsivNtDnPZBNInG2kMIOluIT/3+M4E89sE/bhVIHActYSVwpJuEK1tY7FqYpDBjZVvSZ3Nf6P4CLVnsGe9QooEwtdkHUgajqaRijSuqxMjWtDFPK0nhcHOBBq13kZUihbPBeYVHCdnB19CtvQuHH8nfv5VoOyAkoS8DD+KQ2w607sFsxXSslx8A+eMdqUeHAwek0aeQpDkDyqBaNOMivPui1SdVdDkCE/uLKYWI+YB/IQZfXKXNJYNkInEqwhUAwdwvI2UWPzavP/Yl8VPKyE8orS+RDBz31ILu2bPnkWLs9YbPx9DGjRKwHXAmCPWXgwrpw/fBVo9q3Jyjgw8H+RvWOf7bPDnF/wZ3OlH6sry5WSLVHS8r92g2VZBbt/KwIi45SwjmjJIizrzui5IU7z3viz3s8oP7L0yfED7iIr/1P2379dlruNkWKh/UJdM7VRJnWKa5I0pWxHtztR5RRdX5MKAtGVK3K4DHvcZ/xBNEOe2BGxaPe/gFP77JulvjBa5See8gkEE7wFRHL9Q7qZI0WEFzPL+9TE+gLC8PmEU2tfeY7EFRIW4F7O5t5LEZC8I54ko/QVDk=
  app: workout-tracker
  on:
    repo: elogonme/workout-tracker
    branch: main
  skip_cleanup: 'true'
