language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ZwByuT8hATFgYzVxUzAoDCjen18Wa2xFUPH/G3Rezb2Brzwp4Y3kJVkJM+grpuhNPwBd7U7y2IN6KbaOoMY/xSpkuSe8pxJ0Erk2TAi48mH6taeQzrzz7DD4PpDlvN2B+4/YNdiizjochrQ4g83U8/1N0rQ5RKId4aJbjaXB2vDyBSOoPl32idTLJ5LY0wYZuqo4jOBUU+y7d+BR9lqhW1kEjFQjoV9NOkbxqpYosfmmG8P15A0O81lRGarXCZVh90imNz+P/M2TISkTfCe6aEbpnZ2bcxxCHQa11d+cusY9E2ArsFM0xLXdKZ92UjcXWePvXy00ezSXhPNqEbQ+xJ8QB1rJr690ImWKMHnZtw/jeW+6/Vl/PaNsGgJ7s8C64N2s+IH8JqbzRshhLVBkOClT6RvmMFiEwpzbT+H3VrPy83JbDUKQjLdgWLWgoEJsrsY7r7EEFENrxJdGokmyoUIkAGVEsh2+HnlsZu2QnoUliDRRJPRfx+qylAscbFk4n7hQbiRtA+DKBAYi9QOc+vI5SzGcow5hNH+J3FX3dMU3Ut7HsKEHQpOxmqrpju+PJqP1We/fINdo2fcRn2YXRbgczyVHTOsERXBq1iWJ+iQX/ge4HjXQGu8YFcURdyDq6E+7YjyPg/7wdirkLVpyKjP/SzbEWg2iWDeC+CLp8vw=
  app: workout-tracker
  on:
    repo: elogonme/workout-tracker
    branch: main
  skip_cleanup: 'true'
